### ISSUE TITLE
Do you need calibration on LIDs that are not connected to a subcatchment?

### ISSUE THREAD

**Issue by FarynD** [FarynD/SWMM2PEST#2]
on the current swmm2pest it shows the LID usage information under the subcatchment (only shows data for one LID, if there are multiple it doesn't work). it does show LID information on the last LID that was added. I'm trying to figure out if there needs to be a separate tree for LIDs off of hydraulics on the UI or if it should be under subcatchments.

**Comment by fdumont7** [comment]
keep a LID tree because some subcatchments use the same LID controls.
